[package]
name = "pingserver"
version = "0.1.0"
authors = ["swlynch"]
edition = "2018"

[dependencies]
iou = { git = "https://github.com/phantomical/iou", branch="custom" }
libc = "0.2"
bytes = "0.4"
